generatorName:
  hsr_generator
PickPlacerName:
  hsr_pickplace
GeneratorPath:
  /home/fshs/catkin_ws/src/hirop_pickandplace/generation_libs/
PickpalcerPath:
  /home/fshs/catkin_ws/devel/lib/
GripperName:
  hsr_grab_operation
GripperPath:
  /home/fshs/catkin_ws/devel/lib/
SerialNo:
  /dev/ttyS0
Baudrate:
  115200
